version: "3.8"
services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: vendure
      POSTGRES_PASSWORD: vendure
      POSTGRES_DB: vendure
    ports:
      - 5432:5432
